```{r evalue, cache=cacheon}

evalfunc <- function(time, event, eventname) {
  ## adjusted
  amod <- with(imp, coxph(formula(paste0(
    "Surv(", time, ",", event, " == 'Yes') ~ shf_anemia +",
    paste(modvars, collapse = " + ")
  ))))

  ## df the number of events minus the regression coefficients.
  ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
  asmod <- summary(pool(amod,
    dfcom =
      (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
  ))

  evalc <- evalue(HR(exp(asmod$estimate[1]), rare = FALSE),
    lo = exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]),
    hi = exp(asmod$estimate[1] + global_z05 * asmod$std.error[1])
  )

  oute <- bind_cols(c("Model estimates", "E-values"), as_tibble(fn(evalc, 2)))
  colnames(oute) <- c("", "RR*", "Lower CI", "Upper CI")

  outmod <- tibble(
    Variable = asmod$term,
    hr = paste0(
      fn(exp(asmod$estimate), dig = 2),
      " (", fn(exp(asmod$estimate - global_z05 * asmod$std.error), dig = 2),
      "-", fn(exp(asmod$estimate + global_z05 * asmod$std.error), dig = 2), "), ",
      fn(asmod$p.value, dig = 3, p = TRUE)
    )
  )

  colnames(outmod) <- c("Variable", "HR (95% CI), p-value")

  out <- list(oute = oute, outmod = outmod)

  return(out)
}

death <- evalfunc(
  time = "sos_outtime_death6y",
  event = "sos_out_death6y",
  eventname = "All-cause mortality"
)
anyhosp <- evalfunc(
  time = "sos_outtime_hospany6y",
  event = "sos_out_hospany6y",
  eventname = "First all-cause hospitalization"
)
```

```{r evalueprint1, cache=cacheon, dependson="evalue"}
oute <- cbind(
  death$oute,
  anyhosp$oute[, 2:4]
)

footnote(default_kable(oute,
  scale_down = F,
  font_size = 8,
  caption = "Residual confounding - E-value"
) %>%
  add_header_above(c(" " = 1, "All-cause mortality" = 3, "All-cause hospitalization" = 3)),
symbol = "Approximate conversions of the HR to RR are applied, assuming a non-rare outcome"
)
```

```{r evalueprint2, cache=cacheon, dependson="evalue"}
outmod <- cbind(
  death$outmod,
  anyhosp$outmod[, 2]
)

default_kable(outmod,
  scale_down = F,
  font_size = 8,
  caption = "HR for variables included in the model (for comparison with the magnitude of the E-value)"
) %>%
  add_header_above(c(" " = 1, "All-cause mortality" = 1, "All-cause hospitalization" = 1))
```
