```{r km, cache=cacheon}

kmfunc <- function(time, event, eventcr = NULL, eventname, yposplus = rep(0, 2)) {

  # cox for print
  ## crude
  cmod <- summary(coxph(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ shf_anemia")),
    data = rsdata
  ))
  cp <- paste0(
    "Crude HR (95% CI), p: ",
    fn(cmod$conf.int[1, 1], dig = 1),
    " (", fn(cmod$conf.int[1, 3], dig = 1),
    "-", fn(cmod$conf.int[1, 4], dig = 1), "), ",
    fn(cmod$coef[1, 5], dig = 3, p = TRUE)
  )

  ## adjusted
  tmpamod <- with(imp, coxph(formula(paste0(
    "Surv(", time, ",", event, " == 'Yes') ~ shf_anemia +",
    paste(modvars, collapse = " + ")
  ))))

  ## df the number of events minus the regression coefficients.
  ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
  amod <- summary(pool(tmpamod,
    dfcom =
      (tmpamod$analyses[[1]]$nevent - length(tmpamod$analyses[[1]]$coefficients))
  ))

  ap <- paste0(
    "Adjusted HR (95% CI), p: ",
    fn(exp(amod$estimate[1]), dig = 1),
    " (", fn(exp(amod$estimate[1] - global_z05 * amod$std.error[1]), dig = 1),
    "-", fn(exp(amod$estimate[1] + global_z05 * amod$std.error[1]), dig = 1), "), ",
    fn(amod$p.value[1], dig = 3, p = TRUE)
  )

  # and the curves...
  fits <- survfit(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ shf_anemia")),
    data = rsdata
  ) # needed also for cuminc for n at risk

  if (!is.null(eventcr)) {
    fit <- cuminc(
      ftime = rsdata %>% pull(!!sym(time)),
      fstatus = rsdata %>% pull(!!sym(eventcr)),
      cencode = 0,
      group = rsdata %>% pull(shf_anemia)
    )

    # c(bottom, left, top, right)
    par(mar = c(6, 4, 1, 4.5) + 0.1)

    plot(fit[1:2],
      ylab = eventname,
      col = global_kicols,
      wh = c(1110, 1110),
      xlim = c(0, 6 * 365),
      ylim = c(0, 1),
      xlab = "Years",
      axes = F,
      lwd = 3,
      lty = c(1, 2),
      xaxs = "i", yaxs = "i"
    )
  } else {
    # c(bottom, left, top, right)
    par(mar = c(6, 4, 1, 4.5) + 0.1)
    plots <- plot(fits,
      fun = "event",
      ylab = eventname,
      xscale = 365,
      yscale = 100,
      col = global_kicols,
      mark.time = FALSE,
      bty = "n",
      xlim = c(0, 6 * 365),
      ylim = c(0, 1),
      xlab = "Years",
      axes = F,
      lwd = 3,
      lty = c(1, 2),
      xaxs = "i", yaxs = "i"
    )
  }

  axis(2, seq(0, 1, 0.25), seq(0, 100, 25), las = 2)
  axis(1, at = seq(0, 6, 1) * 365, seq(0, 6, 1))

  if (!is.null(eventcr)) {
    ypos <- timepoints(fit[1:2], 364.5 * 6)$est
  } else {
    ypos <- 1 - summary(fits, 364.5 * 6)$surv
  }

  ylabs <- bind_cols(
    ypos = c(ypos + yposplus),
    ytext = c("No anemia", "Anemia")
  )

  mtext(
    side = 4,
    line = .2,
    at = ylabs$ypos,
    ylabs$ytext,
    las = 1
  )

  mtext("No. at risk", side = 1, line = 3, at = -310, adj = 0, cex = 1)

  mtext("No", side = 1, line = 4, at = -290, adj = 0, cex = 1)
  mtext("Yes", side = 1, line = 5, at = -290, adj = 0, cex = 1)

  nrisk <- summary(fits, seq(0, 6, 1) * 365)$n.risk

  axis(1, at = seq(0, 6, 1) * 365, labels = nrisk[1:7], line = 3, tick = FALSE, cex.axis = 1)
  axis(1, at = seq(0, 6, 1) * 365, labels = nrisk[8:14], line = 4, tick = FALSE, cex.axis = 1)

  text(0 * 365, 0.95, cp, pos = 4)
  text(0 * 365, 0.90, ap, pos = 4)
}
```

```{r kmdeath, fig.cap="All-cause mortality", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_death6y",
  event = "sos_out_death6y",
  eventname = "All-cause mortality (%)",
  yposplus = c(0, 0)
)
```

```{r kmhospany, fig.cap="All-cause hospitalization", cache=cacheon, dependson="km"}
kmfunc(
  time = "sos_outtime_hospany6y",
  event = "sos_out_hospany6y",
  eventcr = "sos_out_hospany6y_cr",
  eventname = "First all-cause hospitalization (%)",
  yposplus = c(0, 0)
)
```
