```{r outforestsub, cache=cacheon}
survmysub <- function(time, event, xvar, xvarname) {
  levs <- levels(rsdata %>% pull(!!sym(xvar)))

  out <- data.frame(matrix(NA, ncol = 6, nrow = length(levs) + 1))
  colnames(out) <- c("Subgroup", "HR (95% CI)", "p", "coef", "lci", "uci")

  out[1, 1] <- xvarname

  for (i in seq_along(levs)) {
    out[1 + i, 1] <- paste0("  ", levs[i])

    amod <- with(imp, coxph(formula(paste0(
      "Surv(", time, ",", event, " == 'Yes') ~ shf_anemia  * relevel(", xvar, ", ref = '", levs[i], "') +",
      paste(modvars[modvars != xvar], collapse = " + ")
    ))))

    ## df the number of events minus the regression coefficients.
    ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
    asmod <- summary(pool(amod,
      dfcom =
        (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
    ))

    out[1 + i, 2] <- paste0(
      fn(exp(asmod$estimate[1]), dig = 1),
      " (", fn(exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]), dig = 1),
      "-", fn(exp(asmod$estimate[1] + global_z05 * asmod$std.error[1]), dig = 1), ")"
    )

    out[1 + i, 4] <- asmod$estimate[1]
    out[1 + i, 5] <- asmod$estimate[1] - global_z05 * asmod$std.error[1]
    out[1 + i, 6] <- asmod$estimate[1] + global_z05 * asmod$std.error[1]

    if (i == 1) {
      if (length(levs) == 2) {
        out[1, 3] <- fn(last(asmod$p.value), dig = 3, p = TRUE)
      } else {
        amodnoint <- with(imp, coxph(formula(paste0(
          "Surv(", time, ",", event, " == 'Yes') ~ shf_anemia  + relevel(", xvar, ", ref = '", levs[i], "') +",
          paste(modvars[modvars != xvar], collapse = " + ")
        ))))

        int <- D1(amod, amodnoint)

        out[1, 3] <- fn(int$result[4], dig = 3, p = TRUE)
      }
    }
  }
  return(out)
}

survmysub2 <- function(time2, event2) {
  forestdata <- survmysub(
    time = time2,
    event = event2,
    xvar = "shf_sex",
    xvarname = "Gender"
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_age_cat",
      xvarname = "Age (years)"
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_nyha_cat",
      xvarname = "NYHA class"
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_ef_cat",
      xvarname = "EF (%)"
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_gfrckdepi_cat",
      xvarname = "eGFR (mL/min/1.73m2)"
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_ntprobnp_cat",
      xvarname = "NT-proBNP"
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "sos_com_cancer3y",
      xvarname = "Malignant cancer"
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_sos_com_diabetes",
      xvarname = "Diabetes"
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "sos_com_liver",
      xvarname = "Liver disease"
    )
  )

  forestdata <- rbind(
    forestdata,
    survmysub(
      time = time2,
      event = event2,
      xvar = "shf_sos_com_ihd",
      xvarname = "IHD"
    )
  )
}
```

```{r outtabsubplot, cache=cacheon, dependson="outforestsub"}
plotforest <- function(forestdata) {
  cextext <- 1

  minmy <- round(exp(min(forestdata$lci, na.rm = T)), 1)
  maxmy <- round(exp(max(forestdata$uci, na.rm = T)), 1)

  # c(bottom, left, top, right)
  par(mar = c(5, 17, 1, 2) + 0.2)


  plot(rev(forestdata$coef), 1:nrow(forestdata),
    cex = 1.5,
    xlim = c(
      log(minmy),
      log(maxmy)
    ),
    xlab = NA,
    ylim = c(1, nrow(forestdata) + .4),
    axes = FALSE,
    ylab = NA,
    main = NA,
    type = "p",
    pch = 22,
    bg = global_kicols[1],
    col = global_kicols[1]
  )

  for (i in 1:nrow(forestdata)) {
    if (!is.na(rev(forestdata$lci)[i])) {
      matplot(c(rev(forestdata$lci)[i], rev(forestdata$uci)[i]), c(i, i),
        type = "l", add = TRUE, col = global_kicols[1], cex = 1
      )
    }
  }

  matplot(c(log(1), log(1)), c(-1, nrow(forestdata)), type = "l", lwd = 1, lty = 3, add = TRUE, col = 1)

  axismy <- seq(minmy, maxmy, 0.1)
  axismy2 <- axismy
  axismy2[!axismy %in% c(minmy, maxmy)] <- NA

  axis(1,
    cex.axis = cextext, at = log(axismy),
    labels = axismy2
  )
  axis(1,
    cex.axis = cextext, at = log(1),
    labels = 1
  )

  axis(2,
    at = c(1:nrow(forestdata), nrow(forestdata) + 1),
    labels = c(rev(forestdata$Subgroup), "Subgroup"),
    cex.axis = cextext, tick = FALSE, las = 2, line = 16, hadj = 0
  )

  axis(2,
    at = c(1:nrow(forestdata), nrow(forestdata) + 1),
    labels = c(rev(forestdata$`HR (95% CI)`), "HR (95% CI)"),
    cex.axis = cextext, tick = FALSE, las = 2, line = 6, hadj = 0.5
  )

  axis(2,
    at = c(1:nrow(forestdata), nrow(forestdata) + 1),
    labels = c(rev(forestdata$p), "P interaction"),
    cex.axis = cextext, tick = FALSE, las = 1, line = 0.5, hadj = 0.5
  )

  axis(1,
    at = 0 - 0.03, cex.axis = cextext,
    labels = "No anemia", line = 1, tick = FALSE, hadj = 1
  )
  axis(1,
    at = 0 + 0.03, cex.axis = cextext,
    labels = "Anemia", line = 1, tick = FALSE, hadj = 0
  )
  axis(1,
    at = 0, cex.axis = cextext,
    labels = "worse", line = 2, tick = FALSE, hadj = 0.5
  )

  text(0, (nrow(forestdata) + 0.9), "HR (95% CI)", cex = cextext)
}
```

```{r outtabsubdeath, cache=cacheon, dependson="outforestsub"}
deathforest <- survmysub2(
  time2 = "sos_outtime_death6y",
  event2 = "sos_out_death6y"
)
```

```{r forestdeath, cache=cacheon, dependson=c("outforestsub", "outtabsubdeath", "outtabsubplot"), fig.cap="Association between anemia and all-cause mortality within subgroups", fig.width=6, fig.height=8}
plotforest(forestdata = deathforest)
```

```{r outtabsubhosp, cache=cacheon, dependson="outforestsub"}
hospforest <- survmysub2(
  time2 = "sos_outtime_hospany6y",
  event2 = "sos_out_hospany6y"
)
```

```{r foresthosp, cache=cacheon, dependson=c("outforestsub", "outtabsubhosp", "outtabsubplot"), fig.cap="Association between anemia and all-cause hospitalization within subgroups", fig.width=6, fig.height=8}
plotforest(hospforest)
```
