```{r outtabfunc, cache=cacheon}
survfunc <- function(data = rsdata, impdata = imp, novars = NULL, time, event, eventcr = NULL, eventname) {
  out <- data.frame(matrix(NA, ncol = 4, nrow = ifelse(is.null(eventcr), 8, 7)))

  out[1, 1] <- eventname
  colnames(out) <- c("Outcome", "Model", levels(rsdata$shf_anemia))

  ## 30, 90 days, 1, 3, 5 yr mort

  out[1:5, 2] <- paste("% (95% CI) at ", c("30days", "90days", "1yr", "3yr", "5yr"))

  fit <- survfit(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ shf_anemia")),
    data = data
  )

  sfit <- summary(fit, times = c(30, 90, 365, 365 * 3, 365 * 5))

  out[1:5, 3:4] <- paste0(
    fn(100 - sfit$surv * 100, dig = 1), " (",
    fn(100 - sfit$upper * 100, dig = 1), "-",
    fn(100 - sfit$lower * 100, dig = 1), ")"
  )

  ## incidence rate
  out[6, 2] <- "No events, sum py, incidence rate/1000py (95% CI)"

  ev <- data %>%
    group_by(shf_anemia) %>%
    summarise(
      ev = sum(!!sym(event) == "Yes"),
      .groups = "rowwise"
    )

  s <- data %>%
    group_by(shf_anemia) %>%
    summarise(
      s = sum(!!sym(time) / 365.25),
      .groups = "rowwise"
    )
  r <- pois.exact(x = ev$ev, pt = s$s / 1000)

  out[6, 3:4] <- paste0(
    ev$ev, ", ",
    fn(s$s, dig = 0), ", ",
    fn(r$rate, dig = 0), " (",
    fn(r$lower, dig = 0), "-",
    fn(r$upper, dig = 0), ")"
  )

  # cox regressions
  lev <- levels(rsdata$shf_sex)
  out[7, 2] <- "Crude HR (95% CI), p-value"
  out[8, 2] <- "Adjusted HR (95% CI), p-value"

  ## crude
  mod <- coxph(formula(paste0("Surv(", time, ",", event, "=='Yes') ~ shf_anemia")),
    data = data
  )
  smod <- summary(mod)

  out[7, 3:4] <- c("ref", paste0(
    fn(smod$conf.int[1, 1], dig = 2),
    " (", fn(smod$conf.int[1, 3], dig = 2),
    "-", fn(smod$conf.int[1, 4], dig = 2), "), ",
    fn(smod$coef[1, 5], dig = 3, p = TRUE)
  ))

  ## adjusted
  amod <- with(impdata, coxph(formula(paste0(
    "Surv(", time, ",", event, " == 'Yes') ~ shf_anemia +",
    paste(setdiff(modvars, novars), collapse = " + ")
  ))))

  ## df the number of events minus the regression coefficients.
  ## There is support for this from middle of page 149 of the book by Parmer & Machin (ISBN 0471936405)
  asmod <- summary(pool(amod,
    dfcom =
      (amod$analyses[[1]]$nevent - length(amod$analyses[[1]]$coefficients))
  ))

  out[8, 3:4] <- c("ref", paste0(
    fn(exp(asmod$estimate[1]), dig = 2),
    " (", fn(exp(asmod$estimate[1] - global_z05 * asmod$std.error[1]), dig = 2),
    "-", fn(exp(asmod$estimate[1] + global_z05 * asmod$std.error[1]), dig = 2), "), ",
    fn(asmod$p.value[1], dig = 3, p = TRUE)
  ))

  if (!is.null(eventcr)) {
    out[9, 2] <- "Adjusted, death as competing event, HR (95% CI), p-value"

    nams <- names(mice::complete(imp, 1))
    modvarscr <- setdiff(nams[str_detect(nams, "_cr_")], novars)

    mod <- crr_mids_hf(
      event = eventcr,
      time = time,
      xvars = modvarscr,
      data = impdata
    )

    smod <- summary(pool(mod))

    out[9, 3:4] <- c("ref", paste0(
      fn(exp(smod$estimate[1]), dig = 2),
      " (", fn(exp(smod$estimate[1] - global_z05 * smod$std.error[1]), dig = 2),
      "-", fn(exp(smod$estimate[1] + global_z05 * smod$std.error[1]), dig = 2), "), ",
      fn(smod$p.value[1], dig = 3, p = TRUE)
    ))
  }
  return(out)
}
```

```{r outtab, cache=cacheon, dependson="outtabfunc"}
death <- survfunc(
  time = "sos_outtime_death6y",
  event = "sos_out_death6y",
  eventname = "All-cause mortality"
)
anyhosp <- survfunc(
  time = "sos_outtime_hospany6y",
  event = "sos_out_hospany6y",
  eventcr = "sos_out_hospany6y_cr",
  eventname = "First all-cause hospitalization"
)

outall <- rbind(
  death,
  anyhosp
)

write.xlsx(outall, paste0("./output/tabs/out_", Sys.Date(), ".xlsx"), rowNames = FALSE)

default_kable(outall,
  font_size = 6,
  caption = "Association between anemia and outcomes"
)
```

```{r outtabunder80, cache=cacheon, dependson="outtabfunc"}
death <- survfunc(
  data = rsdata %>% filter(shf_age < 80), 
  impdata = impunder80, 
  novars = c("shf_age_cat", "shf_age_cat_cr_over75"), 
  time = "sos_outtime_death6y",
  event = "sos_out_death6y",
  eventname = "All-cause mortality"
)
anyhosp <- survfunc(
  data = rsdata %>% filter(shf_age < 80), 
  impdata = impunder80, 
  novars = c("shf_age_cat", "shf_age_cat_cr_over75"), 
  time = "sos_outtime_hospany6y",
  event = "sos_out_hospany6y",
  eventcr = "sos_out_hospany6y_cr",
  eventname = "First all-cause hospitalization"
)

outall <- rbind(
  death,
  anyhosp
)

write.xlsx(outall, paste0("./output/tabs/out_under80_", Sys.Date(), ".xlsx"), rowNames = FALSE)

default_kable(outall,
  font_size = 6,
  caption = "Association between anemia and outcomes - patients < 80 years"
)
```

```{r outtabover80, cache=cacheon, dependson="outtabfunc"}
death <- survfunc(
  data = rsdata %>% filter(shf_age >= 80), 
  impdata = impover80, 
  novars = c("shf_age_cat", "shf_age_cat_cr_over75"), 
  time = "sos_outtime_death6y",
  event = "sos_out_death6y",
  eventname = "All-cause mortality"
)
anyhosp <- survfunc(
  data = rsdata %>% filter(shf_age >= 80), 
  impdata = impover80, 
  novars = c("shf_age_cat", "shf_age_cat_cr_over75"), 
  time = "sos_outtime_hospany6y",
  event = "sos_out_hospany6y",
  eventcr = "sos_out_hospany6y_cr",
  eventname = "First all-cause hospitalization"
)

outall <- rbind(
  death,
  anyhosp
)

write.xlsx(outall, paste0("./output/tabs/out_over80_", Sys.Date(), ".xlsx"), rowNames = FALSE)

default_kable(outall,
  font_size = 6,
  caption = "Association between anemia and outcomes - patients >= 80 years"
)
```